# Generated by Django 6.0.2 on 2026-02-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_options_blog_updated_at_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Health', 'Health'), ('Travel', 'Travel'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle'), ('Sports', 'Sports'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
